// import { GetStaticProps } from 'next'
import Head from 'next/head'
// import { fetchSettings, fileUrl } from '@/lib//sanity'
// import Link from 'next/link'

// interface DataProps extends Awaited<ReturnType<typeof getData>> {}

// interface Props extends DataProps {}

// const getData = async () => {
//   const settings = await fetchSettings()
//   return {
//     settings,
//   }
// }

// export const getStaticProps: GetStaticProps<DataProps> = async () => {
//   return {
//     props: await getData(),
//   }
// }

// export default function Home({ settings }: Props) {
//   const links = settings?.links?.filter((item) => item._type !== 'file' || item.asset) || []

//   return (
//     <>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <main>
//         {(links.length && (
//           <ul>
//             {links.map((item, i) => (
//               <li key={i}>
//                 {item._type === 'file' ? (
//                   <a href={fileUrl(item)} target="_blank">
//                     {item.name}
//                   </a>
//                 ) : (
//                   <a href={item.url} target="_blank">
//                     {item.label}
//                   </a>
//                 )}
//               </li>
//             ))}
//           </ul>
//         )) ||
//           undefined}
//         <nav>
//           <ul>
//             {(settings?.navigation || []).map(({ slug, title }, i) => (
//               <li key={i}>
//                 <Link
//                   href={{
//                     pathname: '/i/[slug]',
//                     query: { slug },
//                   }}
//                 >
//                   {title}
//                 </Link>
//               </li>
//             ))}
//           </ul>
//         </nav>
//       </main>
//     </>
//   )
// }

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>index</main>
    </>
  )
}
